'use client';

import { useState } from 'react';
import {
  Target,
  Users,
  Globe,
  DollarSign,
  MessageSquare,
  Hash,
  Palette,
  TrendingUp,
  Lightbulb,
  Copy,
  Check,
  Printer,
  RefreshCw,
  MapPin,
  Languages,
  Calendar,
  Eye,
  BarChart3,
  Sparkles,
  X,
} from 'lucide-react';
import { toast } from 'sonner';
import type { AdPlan } from '@/lib/ad-plan-generator';

interface AdPlanResultsProps {
  plan: AdPlan;
  businessName: string;
  budget: number;
  currency: string;
  onRegenerate?: () => void;
}

const CURRENCY_SYMBOLS: Record<string, string> = {
  NGN: '₦',
  USD: '$',
  GBP: '£',
  KES: 'KSh',
  GHS: 'GH₵',
};

const PLATFORM_COLORS: Record<string, string> = {
  Facebook: '#1877F2',
  Instagram: '#E4405F',
  TikTok: '#010101',
  Google: '#4285F4',
};

const GOAL_BADGES: Record<string, string> = {
  'Get More Customers': 'bg-green-500/20 text-green-400',
  'Drive Website Traffic': 'bg-blue-500/20 text-blue-400',
  'Promote an Offer': 'bg-orange-500/20 text-orange-400',
  'Build Brand Awareness': 'bg-purple-500/20 text-purple-400',
  'Get Phone Calls': 'bg-cyan-500/20 text-cyan-400',
};

function CopyButton({ text, label }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success(label || 'Copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy');
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="p-1.5 rounded-md text-muted hover:text-text hover:bg-surface2 transition-colors flex-shrink-0"
      title={label || 'Copy'}
    >
      {copied ? <Check className="w-4 h-4 text-success" /> : <Copy className="w-4 h-4" />}
    </button>
  );
}

function SectionHeader({ icon: Icon, title, color }: { icon: React.ComponentType<{ className?: string }>; title: string; color?: string }) {
  return (
    <div className="flex items-center gap-3 mb-4">
      <div className={`w-9 h-9 rounded-lg flex items-center justify-center ${color || 'bg-primary/10'}`}>
        <Icon className="w-5 h-5 text-primary" />
      </div>
      <h3 className="text-lg font-semibold text-text">{title}</h3>
    </div>
  );
}

export function AdPlanResults({ plan, businessName, budget, currency, onRegenerate }: AdPlanResultsProps) {
  const sym = CURRENCY_SYMBOLS[currency] || currency;
  const [activeTab, setActiveTab] = useState(0);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* SECTION 1 — HEADER CARD */}
      <div className="p-6 rounded-xl border border-border bg-surface">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-xl font-bold text-text">{businessName}</h2>
            <div className="flex items-center gap-3 mt-2">
              <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-medium ${GOAL_BADGES[plan.platforms[0]?.name] || 'bg-primary/20 text-primary'}`}>
                {plan.platforms[0]?.name} Strategy
              </span>
              <span className="text-sm text-muted">{sym}{budget.toLocaleString()}/mo</span>
            </div>
            <p className="text-xs text-muted mt-2 flex items-center gap-1.5">
              <Sparkles className="w-3 h-3" />
              Strategy generated by AI &middot; 5 credits used
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-4 py-2 rounded-lg bg-surface2 text-text text-sm font-medium hover:bg-surface2/80 transition-colors border border-border"
            >
              <Printer className="w-4 h-4" />
              Save as PDF
            </button>
            {onRegenerate && (
              <button
                onClick={onRegenerate}
                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary/10 text-primary text-sm font-medium hover:bg-primary/20 transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
                Regenerate
              </button>
            )}
          </div>
        </div>
      </div>

      {/* SECTION 2 — STRATEGY SUMMARY */}
      <div className="p-6 rounded-xl border border-border bg-surface">
        <SectionHeader icon={Target} title="Strategy Summary" />
        <p className="text-sm text-muted leading-relaxed">{plan.summary}</p>
      </div>

      {/* SECTION 3 — TARGET AUDIENCE */}
      <div className="p-6 rounded-xl border border-border bg-surface">
        <SectionHeader icon={Users} title="Target Audience" />
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
          <div className="p-3 rounded-lg bg-surface2">
            <div className="flex items-center gap-2 mb-1">
              <Target className="w-4 h-4 text-primary" />
              <span className="text-xs text-muted">Age</span>
            </div>
            <p className="text-sm font-semibold text-text">{plan.audience.age_min}–{plan.audience.age_max}</p>
            <p className="text-xs text-muted">Primary: {plan.audience.age_primary}</p>
          </div>
          <div className="p-3 rounded-lg bg-surface2">
            <div className="flex items-center gap-2 mb-1">
              <Users className="w-4 h-4 text-primary" />
              <span className="text-xs text-muted">Gender</span>
            </div>
            <p className="text-sm font-semibold text-text">{plan.audience.gender}</p>
          </div>
          <div className="p-3 rounded-lg bg-surface2">
            <div className="flex items-center gap-2 mb-1">
              <MapPin className="w-4 h-4 text-primary" />
              <span className="text-xs text-muted">Location</span>
            </div>
            <p className="text-sm font-semibold text-text truncate">{plan.audience.location_targeting}</p>
          </div>
          <div className="p-3 rounded-lg bg-surface2">
            <div className="flex items-center gap-2 mb-1">
              <Languages className="w-4 h-4 text-primary" />
              <span className="text-xs text-muted">Languages</span>
            </div>
            <p className="text-sm font-semibold text-text">{plan.audience.languages.join(', ')}</p>
          </div>
        </div>
        <div className="space-y-2">
          <p className="text-xs text-muted italic">{plan.audience.gender_reasoning}</p>
          <p className="text-xs text-muted">{plan.audience.description}</p>
        </div>
      </div>

      {/* SECTION 4 — INTERESTS & BEHAVIORS */}
      <div className="grid lg:grid-cols-2 gap-6">
        <div className="p-6 rounded-xl border border-border bg-surface">
          <SectionHeader icon={Target} title="Interests" />
          <div className="space-y-3">
            {plan.interests.map((interest, i) => (
              <div key={i} className="p-3 rounded-lg bg-surface2">
                <p className="text-sm font-semibold text-text mb-2">{interest.category}</p>
                <div className="flex flex-wrap gap-1.5 mb-2">
                  {interest.specific.map((s, j) => (
                    <span key={j} className="px-2 py-0.5 rounded-full bg-primary/10 text-primary text-xs">
                      {s}
                    </span>
                  ))}
                </div>
                <p className="text-xs text-muted">{interest.reasoning}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="p-6 rounded-xl border border-border bg-surface">
          <SectionHeader icon={Users} title="Behaviors" />
          <div className="flex flex-wrap gap-2">
            {plan.behaviors.map((behavior, i) => (
              <span
                key={i}
                className="px-3 py-1.5 rounded-full bg-surface2 text-text text-sm border border-border"
              >
                {behavior}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* SECTION 5 — PLATFORM RECOMMENDATIONS */}
      <div className="p-6 rounded-xl border border-border bg-surface">
        <SectionHeader icon={Globe} title="Platform Recommendations" />
        <div className="grid sm:grid-cols-2 gap-4">
          {plan.platforms.map((platform, i) => (
            <div
              key={i}
              className={`p-4 rounded-xl border transition-colors ${
                platform.recommended
                  ? 'border-primary/30 bg-primary/5'
                  : 'border-border bg-surface2 opacity-60'
              }`}
            >
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div
                    className="w-8 h-8 rounded-lg flex items-center justify-center text-white text-xs font-bold"
                    style={{ backgroundColor: PLATFORM_COLORS[platform.name] || '#666' }}
                  >
                    {platform.name.charAt(0)}
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-text">{platform.name}</p>
                    <p className="text-xs text-muted">Priority #{platform.priority}</p>
                  </div>
                </div>
                <span
                  className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                    platform.recommended
                      ? 'bg-green-500/20 text-green-400'
                      : 'bg-muted/20 text-muted'
                  }`}
                >
                  {platform.recommended ? 'Recommended' : 'Optional'}
                </span>
              </div>
              <p className="text-xs text-muted mb-3">{platform.reason}</p>
              <div className="flex items-center justify-between">
                <span className="px-2 py-0.5 rounded bg-surface text-xs text-muted border border-border">
                  {platform.ad_format}
                </span>
                {platform.recommended && (
                  <span className="text-lg font-bold text-primary">{platform.budget_percentage}%</span>
                )}
              </div>
              {platform.best_time && (
                <p className="text-xs text-muted mt-2 flex items-center gap-1">
                  <Calendar className="w-3 h-3" />
                  {platform.best_time}
                </p>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* SECTION 6 — BUDGET BREAKDOWN */}
      <div className="p-6 rounded-xl border-2 border-primary/30 bg-surface">
        <SectionHeader icon={DollarSign} title="Budget Breakdown" />
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="p-4 rounded-lg bg-surface2 text-center">
            <p className="text-2xl font-bold text-text">{sym}{plan.budget_breakdown.total.toLocaleString()}</p>
            <p className="text-xs text-muted mt-1">Total Budget</p>
          </div>
          <div className="p-4 rounded-lg bg-surface2 text-center">
            <p className="text-2xl font-bold text-text">{sym}{plan.budget_breakdown.daily_budget.toLocaleString()}</p>
            <p className="text-xs text-muted mt-1">Daily Budget</p>
          </div>
          <div className="p-4 rounded-lg bg-surface2 text-center">
            <p className="text-2xl font-bold text-text">{plan.budget_breakdown.duration_days}</p>
            <p className="text-xs text-muted mt-1">Days</p>
          </div>
        </div>

        <div className="space-y-3 mb-6">
          {plan.budget_breakdown.split.map((item, i) => (
            <div key={i} className="space-y-1.5">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div
                    className="w-3 h-3 rounded-full"
                    style={{ backgroundColor: PLATFORM_COLORS[item.platform] || '#666' }}
                  />
                  <span className="text-sm text-text">{item.platform}</span>
                </div>
                <span className="text-sm font-medium text-text">
                  {sym}{item.amount.toLocaleString()} ({item.percentage}%)
                </span>
              </div>
              <div className="w-full h-2 rounded-full bg-surface2 overflow-hidden">
                <div
                  className="h-full rounded-full transition-all duration-500"
                  style={{
                    width: `${item.percentage}%`,
                    backgroundColor: PLATFORM_COLORS[item.platform] || '#3B82F6',
                  }}
                />
              </div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-3 gap-4 pt-4 border-t border-border">
          <div className="text-center">
            <div className="flex items-center justify-center gap-1 mb-1">
              <Eye className="w-4 h-4 text-primary" />
            </div>
            <p className="text-xs text-muted">Est. Reach</p>
            <p className="text-sm font-semibold text-text">{plan.budget_breakdown.estimated_reach}</p>
          </div>
          <div className="text-center">
            <div className="flex items-center justify-center gap-1 mb-1">
              <BarChart3 className="w-4 h-4 text-primary" />
            </div>
            <p className="text-xs text-muted">Est. Results</p>
            <p className="text-sm font-semibold text-text">{plan.budget_breakdown.estimated_results}</p>
          </div>
          <div className="text-center">
            <div className="flex items-center justify-center gap-1 mb-1">
              <DollarSign className="w-4 h-4 text-primary" />
            </div>
            <p className="text-xs text-muted">Cost Per Result</p>
            <p className="text-sm font-semibold text-text">{plan.budget_breakdown.cost_per_result_estimate}</p>
          </div>
        </div>
      </div>

      {/* SECTION 7 — AD COPIES */}
      <div className="p-6 rounded-xl border border-border bg-surface">
        <SectionHeader icon={MessageSquare} title="Ad Copy Templates" />
        <div className="flex gap-2 mb-4 overflow-x-auto pb-1">
          {plan.ad_copies.map((copy, i) => (
            <button
              key={i}
              onClick={() => setActiveTab(i)}
              className={`px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-colors ${
                activeTab === i
                  ? 'bg-primary text-white'
                  : 'bg-surface2 text-muted hover:text-text'
              }`}
            >
              {copy.platform} — {copy.format}
            </button>
          ))}
        </div>

        {plan.ad_copies[activeTab] && (
          <div className="space-y-4">
            <div className="flex items-start justify-between gap-3 p-4 rounded-lg bg-surface2">
              <div className="flex-1 min-w-0">
                <p className="text-xs text-muted mb-1 uppercase tracking-wider">Headline</p>
                <p className="text-sm font-semibold text-text">{plan.ad_copies[activeTab].headline}</p>
              </div>
              <CopyButton text={plan.ad_copies[activeTab].headline} label="Headline copied" />
            </div>

            {plan.ad_copies[activeTab].hook && (
              <div className="flex items-start justify-between gap-3 p-4 rounded-lg bg-surface2">
                <div className="flex-1 min-w-0">
                  <p className="text-xs text-muted mb-1 uppercase tracking-wider">Hook (First Line)</p>
                  <p className="text-sm text-text italic">&ldquo;{plan.ad_copies[activeTab].hook}&rdquo;</p>
                </div>
                <CopyButton text={plan.ad_copies[activeTab].hook} label="Hook copied" />
              </div>
            )}

            <div className="flex items-start justify-between gap-3 p-4 rounded-lg bg-surface2">
              <div className="flex-1 min-w-0">
                <p className="text-xs text-muted mb-1 uppercase tracking-wider">Body Text</p>
                <p className="text-sm text-text">{plan.ad_copies[activeTab].primary_text}</p>
              </div>
              <CopyButton text={plan.ad_copies[activeTab].primary_text} label="Body copied" />
            </div>

            <div className="flex items-center justify-between p-4 rounded-lg bg-surface2">
              <div className="flex items-center gap-3">
                <p className="text-xs text-muted uppercase tracking-wider">CTA</p>
                <span className="px-3 py-1 rounded-full bg-primary text-white text-xs font-medium">
                  {plan.ad_copies[activeTab].call_to_action}
                </span>
              </div>
              <CopyButton text={plan.ad_copies[activeTab].call_to_action} label="CTA copied" />
            </div>

            <button
              onClick={() => {
                const copy = plan.ad_copies[activeTab];
                const text = [
                  copy.headline,
                  copy.hook ? `\n${copy.hook}` : '',
                  `\n${copy.primary_text}`,
                  `\nCTA: ${copy.call_to_action}`,
                ].join('');
                navigator.clipboard.writeText(text);
                toast.success('Full ad copy copied');
              }}
              className="w-full py-2.5 rounded-lg bg-primary/10 text-primary text-sm font-medium hover:bg-primary/20 transition-colors"
            >
              Copy Full Ad Copy
            </button>
          </div>
        )}
      </div>

      {/* SECTION 8 — KEYWORDS & HASHTAGS */}
      <div className="p-6 rounded-xl border border-border bg-surface">
        <SectionHeader icon={Hash} title="Keywords & Hashtags" />
        <div className="grid lg:grid-cols-2 gap-6">
          <div>
            <div className="flex items-center justify-between mb-3">
              <p className="text-sm font-medium text-text">Google Search Keywords</p>
              <CopyButton text={plan.keywords.google_search.join('\n')} label="Keywords copied" />
            </div>
            <div className="flex flex-wrap gap-1.5">
              {plan.keywords.google_search.map((kw, i) => (
                <span key={i} className="px-2.5 py-1 rounded-lg bg-blue-500/10 text-blue-400 text-xs border border-blue-500/20">
                  {kw}
                </span>
              ))}
            </div>
          </div>

          <div>
            <div className="flex items-center justify-between mb-3">
              <p className="text-sm font-medium text-text">Social Media Hashtags</p>
              <CopyButton text={plan.keywords.hashtags_social.join(' ')} label="Hashtags copied" />
            </div>
            <div className="flex flex-wrap gap-1.5">
              {plan.keywords.hashtags_social.map((tag, i) => (
                <span key={i} className="px-2.5 py-1 rounded-lg bg-purple-500/10 text-purple-400 text-xs border border-purple-500/20">
                  {tag}
                </span>
              ))}
            </div>
          </div>
        </div>

        {plan.keywords.negative_keywords.length > 0 && (
          <div className="mt-6">
            <p className="text-sm font-medium text-text mb-3">Negative Keywords (Exclude)</p>
            <div className="flex flex-wrap gap-1.5">
              {plan.keywords.negative_keywords.map((kw, i) => (
                <span key={i} className="px-2.5 py-1 rounded-lg bg-red-500/10 text-red-400 text-xs border border-red-500/20 flex items-center gap-1">
                  <X className="w-3 h-3" />
                  {kw}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* SECTION 9 — CREATIVE DIRECTION */}
      <div className="p-6 rounded-xl border border-border bg-surface">
        <SectionHeader icon={Palette} title="Creative Direction" />
        <div className="space-y-5">
          <div>
            <p className="text-sm font-medium text-text mb-2">Visual Style</p>
            <p className="text-sm text-muted">{plan.creative_direction.visual_style}</p>
          </div>

          <div>
            <p className="text-sm font-medium text-text mb-2">Color Palette</p>
            <p className="text-sm text-muted">{plan.creative_direction.colors}</p>
          </div>

          <div>
            <p className="text-sm font-medium text-text mb-3">Content Ideas</p>
            <div className="space-y-2">
              {plan.creative_direction.content_ideas.map((idea, i) => (
                <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-surface2">
                  <span className="w-6 h-6 rounded-full bg-primary/20 text-primary text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                    {i + 1}
                  </span>
                  <p className="text-sm text-text">{idea}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="grid lg:grid-cols-2 gap-4">
            <div className="p-4 rounded-lg bg-green-500/5 border border-green-500/20">
              <p className="text-sm font-medium text-green-400 mb-3">Do&rsquo;s</p>
              <ul className="space-y-2">
                {plan.creative_direction.do.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-muted">
                    <Check className="w-4 h-4 text-green-400 flex-shrink-0 mt-0.5" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-4 rounded-lg bg-red-500/5 border border-red-500/20">
              <p className="text-sm font-medium text-red-400 mb-3">Don&rsquo;ts</p>
              <ul className="space-y-2">
                {plan.creative_direction.dont.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-muted">
                    <X className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* SECTION 10 — KPIs & TIPS */}
      <div className="grid lg:grid-cols-2 gap-6">
        <div className="p-6 rounded-xl border border-border bg-surface">
          <SectionHeader icon={TrendingUp} title="Key Performance Indicators" />
          <div className="space-y-3">
            {plan.kpis.map((kpi, i) => (
              <div key={i} className="flex items-center justify-between p-3 rounded-lg bg-surface2">
                <span className="text-sm text-text">{kpi.metric}</span>
                <span className="text-sm font-semibold text-primary">{kpi.target}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="p-6 rounded-xl border border-border bg-surface">
          <SectionHeader icon={Lightbulb} title="Pro Tips" />
          <div className="space-y-3">
            {plan.tips.map((tip, i) => (
              <div key={i} className="flex items-start gap-3">
                <div className="w-6 h-6 rounded-full bg-yellow-500/20 text-yellow-400 text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                  {i + 1}
                </div>
                <p className="text-sm text-muted">{tip}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
